local map = vim.keymap.set
vim.g.mapleader = " "

map("v", "J", ":m '>+1<CR>gv=gv")
map("v", "K", ":m '<-2<CR>gv=gv")
map("n", "J", "mzJ`z")
map("n", "<C-d>", "<C-d>zz")
map("n", "<C-u>", "<C-u>zz")
map("n", "n", "nzzzv")
map("n", "N", "Nzzzv")
map("x", "<leader>p", [["_dP]])
map("n", "<leader>d", [[:g/^$/d]])
map({"n", "v"}, "<leader>y", [["+y]])
map("n", "<leader>Y", [["+Y]])
map("n", "Q", "<nop>")
map("n", "<leader>l", ":Lazy<CR>")
map("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
map("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })
map("n", "<C-b>", "<cmd> !clear && time cargo run %<CR>", { silent = false})
map("n", "<C-b>", "<cmd> !clear && time swiftc % && ./main<CR>", { silent = false})
map("n", "<C-n>", "<cmd> !clear && time python%<CR>", { silent = false})
map("n", "<C-c>", "<cmd> !clear && time gcc % && ./a.out<CR>", { silent = false})
map("n", "<C-g>", ":Neotree toggle<CR>")
map("n", "<C-i>", ":Telescope keymaps <CR>")
map("n", "<leader>md", ":MarkdownPreview<CR>")
map("n", "<leader>mdt", ":MarkdownPreviewToggle<CR>")
map("n", "<leader>mds", ":MarkdownPreviewStop<CR>")
map("n", "<leader>.", ":BufferLineCycleNext<CR>")
map("n", "<leader>,", ":BufferLineCyclePrev<CR>")

local builtin = require('telescope.builtin')
map('n', '<leader>pf', builtin.find_files, {})
map('n', '<leader><C-p', builtin.git_files, {})
map('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)


-- vim.keymap.set("n", "<C-q>", ":set colorcolumn=80<CR>")
-- vim.keymap.set("n", "<C-w>", ":set colorcolumn=0<CR>")
